# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=26.2-1.1.1
maven_group=at.woodexplosive
archives_base_name=potion-expire-sounds
# Dependencies
# check this on https://fabricmc.net/develop/
fabric_version=0.152.2+26.2

yacl_version=3.9.4+26.2-fabric
mod_menu_version=20.0.0-beta.3
